/**
 * TEMPORARY SAMPLE DATA FOR TESTING
 * 
 * TODO: REMOVE THIS FILE ONCE FIREBASE IS FULLY INTEGRATED
 * 
 * This file provides mock project data for testing the Reports page
 * and other features without requiring Firebase setup.
 * 
 * To disable sample data:
 * 1. Set USE_SAMPLE_DATA = false in reports/page.tsx
 * 2. Delete this file
 * 3. Remove imports of getSampleProjectData
 */

import { EstimatingLine } from "@/components/estimating/EstimatingGrid";

export interface SampleAIUsageLog {
  id: string;
  type: string;
  timestamp: any;
  cost: number;
  tokens?: number;
  duration?: number;
}

export interface SampleProjectData {
  lines: EstimatingLine[];
  aiUsage: SampleAIUsageLog[];
}

// Sample estimating lines for different project types
const sampleLines: Record<string, EstimatingLine[]> = {
  "1": [
    // Downtown Office Building - Structural Steel
    {
      id: "line-1",
      lineId: "L1",
      itemDescription: "Main Column W12x65",
      category: "Columns",
      subCategory: "",
      materialType: "Rolled",
      shapeType: "W",
      sizeDesignation: "W12x65",
      grade: "A992",
      lengthFt: 20,
      lengthIn: 0,
      qty: 8,
      totalWeight: 1040,
      totalSurfaceArea: 520,
      totalLabor: 12.5,
      totalCost: 15600,
      status: "Active",
      coatingSystem: "None",
    },
    {
      id: "line-2",
      lineId: "L2",
      itemDescription: "Floor Beam W16x40",
      category: "Beams",
      subCategory: "",
      materialType: "Rolled",
      shapeType: "W",
      sizeDesignation: "W16x40",
      grade: "A992",
      lengthFt: 30,
      lengthIn: 0,
      qty: 24,
      totalWeight: 2880,
      totalSurfaceArea: 1440,
      totalLabor: 36,
      totalCost: 43200,
      status: "Active",
      coatingSystem: "None",
    },
    {
      id: "line-3",
      lineId: "L3",
      itemDescription: "Girder W18x55",
      category: "Beams",
      subCategory: "",
      materialType: "Rolled",
      shapeType: "W",
      sizeDesignation: "W18x55",
      grade: "A992",
      lengthFt: 40,
      lengthIn: 0,
      qty: 6,
      totalWeight: 1320,
      totalSurfaceArea: 660,
      totalLabor: 15,
      totalCost: 19800,
      status: "Active",
      coatingSystem: "None",
    },
    {
      id: "line-4",
      lineId: "L4",
      itemDescription: "Angle Bracing L4x4x1/4",
      category: "Misc Metals",
      subCategory: "Brace",
      materialType: "Rolled",
      shapeType: "L",
      sizeDesignation: "L4x4x1/4",
      grade: "A36",
      lengthFt: 12,
      lengthIn: 0,
      qty: 32,
      totalWeight: 512,
      totalSurfaceArea: 256,
      totalLabor: 8,
      totalCost: 7680,
      status: "Active",
      coatingSystem: "None",
    },
    {
      id: "line-5",
      lineId: "L5",
      itemDescription: "Plate Gusset 1/2\"",
      category: "Plates",
      subCategory: "Gusset",
      materialType: "Plate",
      thickness: 0.5,
      width: 12,
      plateLength: 18,
      plateQty: 16,
      plateTotalWeight: 240,
      plateSurfaceArea: 120,
      totalLabor: 4,
      totalCost: 3600,
      status: "Active",
      coatingSystem: "None",
      plateGrade: "A36",
    },
    {
      id: "line-6",
      lineId: "L6",
      itemDescription: "Base Plate 1-1/4\"",
      category: "Plates",
      subCategory: "Base Plate",
      materialType: "Plate",
      thickness: 1.25,
      width: 18,
      plateLength: 18,
      plateQty: 8,
      plateTotalWeight: 320,
      plateSurfaceArea: 160,
      totalLabor: 6,
      totalCost: 4800,
      status: "Active",
      coatingSystem: "None",
      plateGrade: "A36",
    },
  ],
  "2": [
    // Industrial Warehouse - Heavy Structural
    {
      id: "line-1",
      lineId: "L1",
      itemDescription: "Main Frame Column W14x90",
      category: "Columns",
      subCategory: "",
      materialType: "Rolled",
      shapeType: "W",
      sizeDesignation: "W14x90",
      grade: "A992",
      lengthFt: 30,
      lengthIn: 0,
      qty: 12,
      totalWeight: 3240,
      totalSurfaceArea: 1620,
      totalLabor: 45,
      totalCost: 48600,
      status: "Active",
      coatingSystem: "None",
    },
    {
      id: "line-2",
      lineId: "L2",
      itemDescription: "Rafter W18x76",
      category: "Beams",
      subCategory: "",
      materialType: "Rolled",
      shapeType: "W",
      sizeDesignation: "W18x76",
      grade: "A992",
      lengthFt: 50,
      lengthIn: 0,
      qty: 18,
      totalWeight: 6840,
      totalSurfaceArea: 3420,
      totalLabor: 90,
      totalCost: 102600,
      status: "Active",
      coatingSystem: "None",
    },
    {
      id: "line-3",
      lineId: "L3",
      itemDescription: "Purlin C8x13.75",
      category: "Beams",
      subCategory: "",
      materialType: "Rolled",
      shapeType: "C",
      sizeDesignation: "C8x13.75",
      grade: "A36",
      lengthFt: 20,
      lengthIn: 0,
      qty: 60,
      totalWeight: 1650,
      totalSurfaceArea: 825,
      totalLabor: 30,
      totalCost: 24750,
      status: "Active",
      coatingSystem: "None",
    },
    {
      id: "line-4",
      lineId: "L4",
      itemDescription: "Girt C6x10.5",
      category: "Beams",
      subCategory: "",
      materialType: "Rolled",
      shapeType: "C",
      sizeDesignation: "C6x10.5",
      grade: "A36",
      lengthFt: 25,
      lengthIn: 0,
      qty: 48,
      totalWeight: 1260,
      totalSurfaceArea: 630,
      totalLabor: 24,
      totalCost: 18900,
      status: "Active",
      coatingSystem: "None",
    },
    {
      id: "line-5",
      lineId: "L5",
      itemDescription: "Knee Brace L6x6x1/2",
      category: "Misc Metals",
      subCategory: "Brace",
      materialType: "Rolled",
      shapeType: "L",
      sizeDesignation: "L6x6x1/2",
      grade: "A36",
      lengthFt: 8,
      lengthIn: 0,
      qty: 24,
      totalWeight: 768,
      totalSurfaceArea: 384,
      totalLabor: 12,
      totalCost: 11520,
      status: "Active",
      coatingSystem: "None",
    },
    {
      id: "line-6",
      lineId: "L6",
      itemDescription: "Joist WT7x26.5",
      category: "Beams",
      subCategory: "",
      materialType: "Rolled",
      shapeType: "WT",
      sizeDesignation: "WT7x26.5",
      grade: "A992",
      lengthFt: 30,
      lengthIn: 0,
      qty: 20,
      totalWeight: 1590,
      totalSurfaceArea: 795,
      totalLabor: 35,
      totalCost: 23850,
      status: "Active",
      coatingSystem: "None",
    },
  ],
  "3": [
    // Bridge Restoration - Heavy Plates and Beams
    {
      id: "line-1",
      lineId: "L1",
      itemDescription: "Main Girder W36x150",
      category: "Beams",
      subCategory: "",
      materialType: "Rolled",
      shapeType: "W",
      sizeDesignation: "W36x150",
      grade: "A992",
      lengthFt: 60,
      lengthIn: 0,
      qty: 4,
      totalWeight: 3600,
      totalSurfaceArea: 1800,
      totalLabor: 80,
      totalCost: 54000,
      status: "Active",
      coatingSystem: "None",
    },
    {
      id: "line-2",
      lineId: "L2",
      itemDescription: "Cross Beam W24x84",
      category: "Beams",
      subCategory: "",
      materialType: "Rolled",
      shapeType: "W",
      sizeDesignation: "W24x84",
      grade: "A992",
      lengthFt: 20,
      lengthIn: 0,
      qty: 12,
      totalWeight: 2016,
      totalSurfaceArea: 1008,
      totalLabor: 48,
      totalCost: 30240,
      status: "Active",
      coatingSystem: "None",
    },
    {
      id: "line-3",
      lineId: "L3",
      itemDescription: "Deck Plate 3/4\"",
      category: "Plates",
      subCategory: "",
      materialType: "Plate",
      thickness: 0.75,
      width: 48,
      plateLength: 120,
      plateQty: 8,
      plateTotalWeight: 1440,
      plateSurfaceArea: 720,
      totalLabor: 32,
      totalCost: 21600,
      status: "Active",
      coatingSystem: "None",
      plateGrade: "A36",
    },
    {
      id: "line-4",
      lineId: "L4",
      itemDescription: "Stiffener Plate 1/2\"",
      category: "Plates",
      subCategory: "Stiffener",
      materialType: "Plate",
      thickness: 0.5,
      width: 6,
      plateLength: 24,
      plateQty: 40,
      plateTotalWeight: 400,
      plateSurfaceArea: 200,
      totalLabor: 10,
      totalCost: 6000,
      status: "Active",
      coatingSystem: "None",
      plateGrade: "A36",
    },
    {
      id: "line-5",
      lineId: "L5",
      itemDescription: "Bearing Plate 1-1/2\"",
      category: "Plates",
      subCategory: "Base Plate",
      materialType: "Plate",
      thickness: 1.5,
      width: 24,
      plateLength: 24,
      plateQty: 8,
      plateTotalWeight: 480,
      plateSurfaceArea: 240,
      totalLabor: 12,
      totalCost: 7200,
      status: "Active",
      coatingSystem: "None",
      plateGrade: "A36",
    },
    {
      id: "line-6",
      lineId: "L6",
      itemDescription: "Diagonal Brace L5x5x3/8",
      category: "Misc Metals",
      subCategory: "Brace",
      materialType: "Rolled",
      shapeType: "L",
      sizeDesignation: "L5x5x3/8",
      grade: "A36",
      lengthFt: 15,
      lengthIn: 0,
      qty: 16,
      totalWeight: 600,
      totalSurfaceArea: 300,
      totalLabor: 8,
      totalCost: 9000,
      status: "Active",
      coatingSystem: "None",
    },
  ],
};

// Sample AI usage logs
const sampleAIUsage: Record<string, SampleAIUsageLog[]> = {
  "1": [
    {
      id: "ai-1",
      type: "whisper",
      timestamp: { toDate: () => new Date(Date.now() - 86400000) }, // 1 day ago
      cost: 0.024,
      duration: 4,
    },
    {
      id: "ai-2",
      type: "spec-review",
      timestamp: { toDate: () => new Date(Date.now() - 172800000) }, // 2 days ago
      cost: 0.15,
      tokens: 1250,
    },
    {
      id: "ai-3",
      type: "proposal",
      timestamp: { toDate: () => new Date(Date.now() - 259200000) }, // 3 days ago
      cost: 0.08,
      tokens: 800,
    },
  ],
  "2": [
    {
      id: "ai-1",
      type: "whisper",
      timestamp: { toDate: () => new Date(Date.now() - 43200000) }, // 12 hours ago
      cost: 0.036,
      duration: 6,
    },
    {
      id: "ai-2",
      type: "spec-review",
      timestamp: { toDate: () => new Date(Date.now() - 86400000) }, // 1 day ago
      cost: 0.18,
      tokens: 1500,
    },
    {
      id: "ai-3",
      type: "proposal",
      timestamp: { toDate: () => new Date(Date.now() - 172800000) }, // 2 days ago
      cost: 0.12,
      tokens: 1200,
    },
    {
      id: "ai-4",
      type: "spec-review",
      timestamp: { toDate: () => new Date(Date.now() - 345600000) }, // 4 days ago
      cost: 0.22,
      tokens: 1800,
    },
  ],
  "3": [
    {
      id: "ai-1",
      type: "whisper",
      timestamp: { toDate: () => new Date(Date.now() - 21600000) }, // 6 hours ago
      cost: 0.048,
      duration: 8,
    },
    {
      id: "ai-2",
      type: "spec-review",
      timestamp: { toDate: () => new Date(Date.now() - 43200000) }, // 12 hours ago
      cost: 0.25,
      tokens: 2100,
    },
    {
      id: "ai-3",
      type: "proposal",
      timestamp: { toDate: () => new Date(Date.now() - 86400000) }, // 1 day ago
      cost: 0.15,
      tokens: 1500,
    },
  ],
};

/**
 * Get sample project data for a given project ID
 * Returns default data if project ID not found
 */
export function getSampleProjectData(projectId: string): SampleProjectData {
  return {
    lines: sampleLines[projectId] || sampleLines["1"] || [],
    aiUsage: sampleAIUsage[projectId] || sampleAIUsage["1"] || [],
  };
}
