"use client";

import { useParams, useSearchParams } from "next/navigation";
import EstimatingGrid from "@/components/estimating/EstimatingGrid";
import KPISummary from "@/components/estimating/KPISummary";
import { Save, Upload, ArrowLeft } from "lucide-react";
import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import Button from "@/components/ui/Button";
import { subscribeToCollection, createDocument, updateDocument, deleteDocument, getDocument, getDocRef } from "@/lib/firebase/firestore";
import { onSnapshot } from "firebase/firestore";
import { getProjectPath } from "@/lib/firebase/firestore";
import { EstimatingLine } from "@/components/estimating/EstimatingGrid";
import { isFirebaseConfigured } from "@/lib/firebase/config";
import { exportToQuant, importFromQuant } from "@/lib/utils/quantExport";
import {
  loadCompanySettings,
  getMaterialRateForGrade,
  getLaborRate,
  getCoatingRate,
  type CompanySettings,
} from "@/lib/utils/settingsLoader";

import { useCompanyId } from "@/lib/hooks/useCompanyId";
import { UserPresence } from "@/components/collaboration/UserPresence";
import { logActivity } from "@/lib/utils/activityLogger";
import ProposalSeedsCard from "@/components/estimating/ProposalSeedsCard";

export default function EstimatingPage() {
  const params = useParams();
  const searchParams = useSearchParams();
  const projectId = params.id as string;
  const companyId = useCompanyId();
  const lineIdFromUrl = searchParams.get("lineId");
  
  const [lines, setLines] = useState<EstimatingLine[]>([]);
  const [projectName, setProjectName] = useState<string>("");
  const [projectNumber, setProjectNumber] = useState<string>("");
  const [companySettings, setCompanySettings] = useState<CompanySettings | null>(null);
  const [selectedLineId, setSelectedLineId] = useState<string | null>(lineIdFromUrl || null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [addLineHandler, setAddLineHandler] = useState<(() => void) | null>(null);

  // Load company settings
  useEffect(() => {
    if (!isFirebaseConfigured() || !companyId) {
      setCompanySettings(null);
      return;
    }
    loadCompanySettings(companyId).then(setCompanySettings);
  }, [companyId]);

  const handleImportEstimate = async () => {
    // Trigger file input click
    fileInputRef.current?.click();
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Reset input so same file can be selected again
    e.target.value = "";

    try {
      // Import the .quant file
      const quantFile = await importFromQuant(file);
      
      if (!quantFile.lines || quantFile.lines.length === 0) {
        alert("The imported file contains no estimate lines.");
        return;
      }

      // Confirm import
      const confirmMessage = `Import estimate with ${quantFile.lines.length} line(s)?\n\nProject: ${quantFile.metadata.projectName || quantFile.metadata.projectId}\nTotal Cost: $${quantFile.metadata.totalCost.toFixed(2)}`;
      if (!confirm(confirmMessage)) {
        return;
      }

      // Save imported lines to Firestore
      if (!isFirebaseConfigured()) {
        alert("Firebase is not configured. Cannot import estimate.");
        return;
      }

      const linesPath = getProjectPath(companyId, projectId, "lines");
      
      // Delete existing lines (optional - you might want to merge instead)
      // For now, we'll add to existing lines
      
      // Create new lines from imported data
      for (const line of quantFile.lines) {
        // Remove id if present (will be generated by Firestore)
        const { id, ...lineData } = line;
        await createDocument(linesPath, lineData);
      }

      alert(`Successfully imported ${quantFile.lines.length} line(s) from ${file.name}`);
    } catch (error: any) {
      console.error("Failed to import estimate:", error);
      alert(`Failed to import estimate: ${error.message || "Unknown error"}`);
    }
  };

  // Load project name and number with real-time subscription
  useEffect(() => {
    if (!isFirebaseConfigured() || !projectId) {
      setProjectName("");
      setProjectNumber("");
      return;
    }

    // Initial load
    const loadProject = async () => {
      try {
        const projectPath = getProjectPath(companyId, projectId);
        const projectData = await getDocument<{ projectName?: string; projectNumber?: string }>(projectPath);
        if (projectData) {
          setProjectName(projectData.projectName || projectId);
          setProjectNumber(projectData.projectNumber || "");
        } else {
          setProjectName(projectId);
          setProjectNumber("");
        }
      } catch (error) {
        console.error("Failed to load project:", error);
        setProjectName(projectId);
        setProjectNumber("");
      }
    };

    loadProject();

    // Real-time subscription
    const projectPath = getProjectPath(companyId, projectId);
    const projectDocRef = getDocRef(projectPath);

    const unsubscribe = onSnapshot(
      projectDocRef,
      (snapshot) => {
        if (snapshot.exists()) {
          const data = snapshot.data();
          setProjectName(data.projectName || projectId);
          setProjectNumber(data.projectNumber || "");
        }
      },
      (error) => {
        console.error("Error subscribing to project:", error);
      }
    );

    return () => unsubscribe();
  }, [companyId, projectId]);

  useEffect(() => {
    if (!isFirebaseConfigured()) {
      setLines([]);
      return () => {};
    }

    const linesPath = getProjectPath(companyId, projectId, "lines");
    const unsubscribe = subscribeToCollection<EstimatingLine>(
      linesPath,
      (data) => {
        setLines(data);
      }
    );

    return () => unsubscribe();
  }, [companyId, projectId]);

  // Log activity when viewing page
  useEffect(() => {
    if (projectId && companyId) {
      logActivity(companyId, projectId, "viewed_estimating");
    }
  }, [projectId, companyId]);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="space-y-6 pb-24">
        {/* User Presence */}
        <div className="flex items-center justify-end">
          <UserPresence projectId={projectId} currentPage="estimating" />
        </div>
        
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-4 min-w-0 flex-shrink">
          <Link href={`/projects/${projectId}`}>
            <Button variant="outline" size="sm" className="gap-2 flex-shrink-0">
              <ArrowLeft className="w-4 h-4" />
              <span className="hidden sm:inline">Project Dashboard</span>
              <span className="sm:hidden">Back</span>
            </Button>
          </Link>
          <div className="min-w-0">
            <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 truncate">Structural Steel Estimate</h1>
            <p className="text-sm text-gray-600 mt-1 truncate">
              {projectNumber ? `${projectNumber} - ` : ""}{projectName || projectId || "N/A"}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-3 flex-shrink-0">
          {/* Import Estimate Button */}
          <button
            onClick={handleImportEstimate}
            className="px-3 sm:px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white flex items-center gap-2 transition-all shadow-md font-medium whitespace-nowrap"
            title="Import estimate from Quant proprietary format (.quant)"
          >
            <Upload className="w-4 h-4 flex-shrink-0" />
            <span className="text-sm hidden sm:inline">Import Estimate</span>
            <span className="text-sm sm:hidden">Import</span>
          </button>
          {/* Hidden file input */}
          <input
            ref={fileInputRef}
            type="file"
            accept=".quant,application/json"
            onChange={handleFileChange}
            className="hidden"
          />
          {/* Save Estimate Button */}
          <button
            onClick={async () => {
              try {
                await exportToQuant(lines, projectId, companyId);
                // Check if browser supports File System Access API
                const supportsSaveDialog = 'showSaveFilePicker' in window;
                if (supportsSaveDialog) {
                  alert("Estimate saved successfully to your chosen location!");
                } else {
                  alert("Estimate saved successfully!\n\nThe file has been downloaded to your default Downloads folder.");
                }
              } catch (error: any) {
                if (error.message === 'Save cancelled') {
                  // User cancelled - don't show error
                  return;
                }
                console.error("Failed to save estimate:", error);
                alert(`Failed to save estimate: ${error.message}`);
              }
            }}
            className="px-3 sm:px-4 py-2 rounded-lg bg-green-600 hover:bg-green-700 text-white flex items-center gap-2 transition-all shadow-md font-medium whitespace-nowrap"
            title="Save estimate in Quant proprietary format (.quant)"
          >
            <Save className="w-4 h-4 flex-shrink-0" />
            <span className="text-sm hidden sm:inline">Save Estimate</span>
            <span className="text-sm sm:hidden">Save</span>
          </button>
        </div>
      </div>


      {/* KPI Summary */}
      <KPISummary 
        lines={lines} 
        onAddLine={addLineHandler || undefined}
        isManualMode={true}
      />

      {/* Estimating Grid - Always on top */}
      <EstimatingGrid 
        companyId={companyId} 
        projectId={projectId}
        isManualMode={true}
        highlightLineId={lineIdFromUrl}
        onAddLineRef={setAddLineHandler}
      />

      {/* Progressive Inclusions/Exclusions - Full Width */}
      <ProposalSeedsCard
        companyId={companyId}
        projectId={projectId}
        selectedLineId={selectedLineId}
        lines={lines}
      />
      </div>
    </div>
  );
}
